name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Critical for letting the token talk to Coveralls/GitHub APIs
      contents: write
      pull-requests: write
      checks: write

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install -e .[dev,all]

    - name: Test with Pytest
      run: |
        pytest tests -v --tb=short

    - name: Generate Coverage
      if: matrix.python-version == '3.12'
      run: |
        pytest --cov=src/chunklet --cov-report=xml tests

    - name: Upload coverage to Coveralls
      if: matrix.python-version == '3.12'
      uses: coverallsapp/github-action@v2.3.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: coverage.xml
        fail-under: 87
        fail-on-decrease: true
        fail-threshold: 1.5
        
